export const SHOW_GRAPHS = 'SHOW_GRAPHS';
export const CLEAR_GRAPHS = 'CLEAR_GRAPHS';
export const SELECT_APP  = 'SELECT_APP';
export const SELECT_POOL = 'SELECT_POOL';
export const SELECT_MACHINE = 'SELECT_MACHINE';
export const SELECT_INSTANCE = 'SELECT_INSTANCE';
